### ISSUE TITLE
This weird dual LICENSE and license thing is a problem

### ISSUE THREAD

**Issue by createthis** [amirfefer/react-ellipsis-with-tooltip#14]
See terminal history:
<img width="1231" alt="Screen Shot 2019-08-29 at 2 36 43 PM" src="https://user-images.githubusercontent.com/1695880/63967018-82b8bd00-ca6a-11e9-9719-a2e1b447e42e.png">

**Comment by amirfefer** [comment]
closing this (https://github.com/amirfefer/react-ellipsis-with-tooltip/pull/13)
