### ISSUE TITLE
I am getting the error as : ./node_modules/react-ellipsis-with-tooltip/dist/index.js Module not found: Can't resolve 'react-bootstrap' in 'C:\XXX\node_modules\react-ellipsis-with-tooltip\dist'

### ISSUE THREAD

**Issue by chandrahaswtw** [amirfefer/react-ellipsis-with-tooltip#16]
I am getting the error as : 

./node_modules/react-ellipsis-with-tooltip/dist/index.js Module not found: Can't resolve 'react-bootstrap' in 'C:\XXX\node_modules\react-ellipsis-with-tooltip\dist'

I can see react-bootstrap as a dependency. Guess this must be installed when I install the package. I've even installed react-bootstrap explicitly, but this ain't working.

Can you please guide me here..!!

**Comment by Avivhdr** [comment]
Same here.
Is react-bootstrap a peer-dependency?

**Comment by amirfefer** [comment]
Hi @chandrahaswtw, @Avivhdr 
Sorry for the delay.
Yes, `react-bootstrap` is a peer-dependency
It should work with versions 0.31 and 0.32

If it still doesn't work for you, please open a follow-up issue
