### ISSUE TITLE
Does not update text if ellipsis already moused over and children change

### ISSUE THREAD

**Issue by createthis** [amirfefer/react-ellipsis-with-tooltip#8]
Does not update text if ellipsis already moused over and children change

**Comment by createthis** [comment]
@amirfefer updated. Also, if I get a vote, I strongly recommend dropping commit lint. Force push is dangerous and this thing is seriously annoying.

**Comment by amirfefer** [comment]
closing this (https://github.com/amirfefer/react-ellipsis-with-tooltip/pull/13)
